name: ft_transcendence

services:
  platform:
    container_name: platform
    build: platform/
    ports:
      - "8080:443"
    volumes:
      - database:/home/db
      - uploads:/home/uploads
    networks:
      - apis
    restart: always

  game:
    container_name: game
    build: game/
    ports:
      - "8081:443"
    networks:
      - apis
    depends_on:
      - platform
    restart: always

  nginx:
    container_name: nginx
    build: nginx/
    volumes:
      - uploads:/var/www/uploads
      - web:/var/www/html
    depends_on:
      - front
    restart: always

  front:
    container_name: front
    build: front/
    volumes:
      - web:/home/app/dist
    depends_on:
      - platform
      - game


volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: ../volumes/database/
      o: bind

  uploads:
    driver: local
    driver_opts:
      type: none
      device: ../volumes/uploads/
      o: bind

  web:
    driver: local
    driver_opts:
      type: none
      device: ../volumes/web/
      o: bind


networks:
  apis:
    driver: bridge
